gcc updated to version 14.4

diff --git a/040-build-gcc b/040-build-gcc
--- a/040-build-gcc
+++ b/040-build-gcc
@@ -5,7 +5,7 @@
 # https://gcc.gnu.org
 #
 P=gcc
-V=${OTB_COMPILER_VERSION:-11.4.0}
+V=${OTB_COMPILER_VERSION:-14.4.0}
 
 trap "otb_exit" EXIT
 
@@ -24,27 +24,26 @@ test -r "${SRC_FILE}" || \
     curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}
 
 if [[ "${OTB_OS}" == 'Linux' ]]; then
-	# GCC on Linux tries to create the directory $OTB_PREFIX/lib64.
-	# So 'make install' fails, if this is a sym-link.
+    # GCC on Linux tries to create the directory $OTB_PREFIX/lib64.
+    # So 'make install' fails, if this is a sym-link.
         if [[ -e ${OTB_PREFIX}/lib64 ]]; then 
-	        rm -v "${OTB_PREFIX}/lib64" || exit ${OTB_ERR_SYSTEM}
+            rm -v "${OTB_PREFIX}/lib64" || exit ${OTB_ERR_SYSTEM}
         fi
-	read OS_ID OS_VERSION < <(bash -c 'source /etc/os-release; printf "%s %s\n" $ID $VERSION')
-	if [[ "${OS_ID}" == 'opensuse-leap' ]]; then
-       		case "${OS_VERSION}" in
-	        	16.0 )
-		  		CC='/usr/bin/gcc-13'
-		       		CXX='/usr/bin/g++-13'
-		        	;;
-			* )
-		  		CC='/usr/bin/gcc'
-		       		CXX='/usr/bin/g++'
-				;;
-		esac
-		export CC CXX
-	fi
-fi       
-
+    read OS_ID OS_VERSION < <(bash -c 'source /etc/os-release; printf "%s %s\n" $ID $VERSION')
+    if [[ "${OS_ID}" == 'opensuse-leap' ]]; then
+            case "${OS_VERSION}" in
+                16.0 )
+                CC='/usr/bin/gcc-13'
+                    CXX='/usr/bin/g++-13'
+                    ;;
+        * )
+                CC='/usr/bin/gcc'
+                    CXX='/usr/bin/g++'
+                ;;
+        esac
+        export CC CXX
+    fi
+fi
 
 # unpack
 mkdir -v -p "${OTB_SRC_DIR}/$P" && cd "$_"  || exit ${OTB_ERR_SYSTEM}
@@ -56,8 +55,8 @@ mkdir -v -p "${OTB_SRC_DIR}/$P/build-$V" && cd "$_"  || exit ${OTB_ERR_SYSTEM}
 # OS dependent args
 declare -a args=()
 if [[ $(uname -s) == Darwin ]]; then
-	sysroot=$(xcrun --show-sdk-path)
-	args+=( "--with-sysroot=${sysroot}" )
+    sysroot=$(xcrun --show-sdk-path)
+    args+=( "--with-sysroot=${sysroot}" )
 fi
 
 "${OTB_SRC_DIR}/$P/$P-$V/configure" \
@@ -65,13 +64,13 @@ fi
         --enable-languages=c,c++,objc,obj-c++,lto,fortran \
         --enable-lto \
         --disable-multilib \
-	--disable-libsanitizer \
+        --disable-libsanitizer \
         --with-build-config=bootstrap-debug \
         --with-gmp="${OTB_PREFIX}" \
         --with-mpfr="${OTB_PREFIX}" \
         --with-mpc="${OTB_PREFIX}" \
-	"${args[@]}" \
-	|| exit ${OTB_ERR_CONFIGURE}
+    "${args[@]}" \
+    || exit ${OTB_ERR_CONFIGURE}
 
 # compile & install
 make -j 2 || exit ${OTB_ERR_MAKE}
